eureka:
  instance:
    hostname: localhost
    prefer-ip-address: 'true'
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
spring:
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/MyDB
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
  application:
    name: auth
  jackson:
    default-property-inclusion: NON_NULL
server:
  port: '9091'
jwt:
  secret: secretkey
  token:
    validity: '86400000'